app/Http/routes.php
<?php


Route::get('login', 'Auth\AuthController@login');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

Route::group(['middleware' => 'auth'], function () {

    Route::get('not-found', 'HomeController@notFound');

    Route::get('/', [
        'as'   => 'home',
        'uses' => 'HomeController@index'
    ]);
    Route::get('my-tasks', [
        'as'   => 'tasks',
        'uses' => 'HomeController@tasks'
    ]);
    Route::get('my-tasks/{id}', [
        'as'   => 'task',
        'uses' => 'HomeController@task'
    ]);
    Route::post('my-tasks/{id}', [
        'as'   => 'task.update',
        'uses' => 'HomeController@taskSave'
    ]);
    Route::get('calendar-tasks', [
        'as'   => 'home.calendar.tasks',
        'uses' => 'HomeController@calendarTasks'
    ]);

    Route::resource('clients', 'ClientController',
        ['only' => ['index', 'show']]);

    Route::get('clients/login/{id}', [
        'as'   => 'clients.login',
        'uses' => 'ClientController@login'
    ]);
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/search/client', [
        'as'   => 'tasks.find.client',
        'uses' => 'TaskController@findClient'
    ]);

    Route::resource('configuration', 'ConfigurationController');

    Route::get('tasks/note/{id}', [
        'as'   => 'tasks.note',
        'uses' => 'TaskController@note'
    ]);
    Route::post('tasks/note/{id}', [
        'as'   => 'tasks.note.save',
        'uses' => 'TaskController@noteSave'
    ]);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');

});

app/Http/Controllers/CategoryController.php
<?php

namespace SAPM\Http\Controllers;

use Prettus\Validator\Exceptions\ValidatorException;
use SAPM\Repositories\CategoryRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    protected $category;

    /**
     * @param CategoryRepository $repository
     */
    public function __construct(CategoryRepository $repository)
    {
        $this->category = $repository;

        $this->setTitleOrDescription('Categories');
        
        $this->middleware('role:administrator');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $categories = $this->category->paginate();

        return $this->view('index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return $this->view('create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $this->category->create($request->all());
        } catch (ValidatorException $e) {
            return $this->redirectBack()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $category = $this->category->find($id);

        return $this->view('edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->category->update($request->all(), $id);
        } catch (ValidatorException $e) {
            return $this->redirectBack()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->category->delete($id);
    }
}

resources/views/category/create.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        {!! Form::open(['route' => 'categories.store','method' => 'POST']) !!}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Category Create</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.text.buttons.save')</button>
                    <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.text.buttons.cancel')</a>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.name')</label>
                        <input type="text" id="name" name="name" class="form-control" value="{!! old('name') !!}">
                    </div>
                    <div class="form-group">
                        <label for="description">@lang('task.text.labels.description')</label>
                        <textarea name="description" id="description" class="form-control" rows="4">{!! old('description') !!}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
</div>
@stop

resources/views/category/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => ['categories.update',$category->id],'method' => 'PUT']) !!}
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Category Update</h3>
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.text.buttons.save')</button>
                        <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.text.buttons.cancel')</a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-md-6 col-md-push-3">
                        <div class="form-group">
                            <label for="name">@lang('task.text.labels.name')</label>
                            <input type="text" id="name" name="name" class="form-control" value="{!! old('name',$category->name) !!}">
                        </div>
                        <div class="form-group">
                            <label for="name">@lang('task.text.labels.description')</label>
                            <textarea name="description" id="description" class="form-control" rows="4">{!! old('description',$category->description) !!}</textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@stop

resources/views/category/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Categories Management</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <a href="{!! route('categories.create') !!}" class="btn btn-primary btn-flat"><i class="fa fa-plus"></i> @lang('task.text.buttons.add_category')</a>
                </div>
            </div>
            <div class="box-body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@lang('task.text.labels.name')</th>
                            <th>@lang('task.text.labels.description')</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                    <tr>
                        <td>{{ $category->name }}</td>
                        <td>{{ $category->description or '-' }}</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a href="{!! route('categories.edit',$category->id) !!}" class="btn btn-default btn-flat">
                                    <i class="fa fa-edit"></i> @lang('task.text.buttons.edit')
                                </a>
                                <button class="btn btn-danger btn-flat" data-btn-type="delete" data-url="{!! route('categories.destroy',$category->id) !!}" data-toggle="confirmation"><i class="fa fa-trash"></i> @lang('task.text.buttons.delete')</button>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4"><p class="text-center">@lang('task.text.no.record')</p></td>
                    </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            @if($paginate = $categories->render())
            <div class="box-footer">
                {!! $paginate !!}
            </div>
            @endif
        </div>
    </div>
</div>
@stop