app/Http/routes.php
<?php


Route::get('login', 'Auth\AuthController@login');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

Route::group(['middleware' => 'auth'], function () {

    Route::get('not-found', 'HomeController@notFound');

    Route::get('/', [
        'as'   => 'home',
        'uses' => 'HomeController@index'
    ]);
    Route::get('my-tasks', [
        'as'   => 'tasks',
        'uses' => 'HomeController@tasks'
    ]);
    Route::get('my-tasks/{id}', [
        'as'   => 'task',
        'uses' => 'HomeController@task'
    ]);
    Route::post('my-tasks/{id}', [
        'as'   => 'task.update',
        'uses' => 'HomeController@taskSave'
    ]);
    Route::get('calendar-tasks', [
        'as'   => 'home.calendar.tasks',
        'uses' => 'HomeController@calendarTasks'
    ]);

    Route::resource('clients', 'ClientController',
        ['only' => ['index', 'show']]);

    Route::get('clients/login/{id}', [
        'as'   => 'clients.login',
        'uses' => 'ClientController@login'
    ]);
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/search/client', [
        'as'   => 'tasks.find.client',
        'uses' => 'TaskController@findClient'
    ]);

    Route::resource('configuration', 'ConfigurationController');

    Route::get('tasks/note/{id}', [
        'as'   => 'tasks.note',
        'uses' => 'TaskController@note'
    ]);
    Route::post('tasks/note/{id}', [
        'as'   => 'tasks.note.save',
        'uses' => 'TaskController@noteSave'
    ]);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');

});

app/Http/Controllers/RoleController.php
<?php

namespace SAPM\Http\Controllers;

use Prettus\Validator\Exceptions\ValidatorException;
use SAPM\Repositories\RoleRepository;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * @var RoleRepository
     */
    protected $role;

    /**
     * @param RoleRepository $repository
     */
    public function __construct(RoleRepository $repository)
    {
        $this->role = $repository;
        $this->middleware('role:administrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $roles = $this->role->paginate();

        $this->setTitleOrDescription('Roles');
        return $this->view('index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $this->setTitleOrDescription('Roles');

        return $this->view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $this->role->create($request->all());
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('roles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $role = $this->role->find($id);

        $this->setTitleOrDescription('Roles');
        return $this->view('edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->role->update($request->all(), $id);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->role->delete($id);
    }
}

resources/views/role/create.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        {!! Form::open(['route' => 'roles.store','method' => 'POST']) !!}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Role Create</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.text.buttons.save')</button>
                    <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.text.buttons.cancel')</a>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.name')</label>
                        <input type="text" id="name" name="name" class="form-control" value="{!! old('name') !!}">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.level')</label>
                        <input type="number" id="level" name="level" class="form-control" value="{!! old('level') !!}">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.description')</label>
                        <textarea name="description" id="description" class="form-control" rows="4">{!! old('description') !!}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
</div>
@stop

resources/views/role/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        {!! Form::open(['route' => ['roles.update',$role->id],'method' => 'PUT']) !!}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Role Edit - {!! $role->name !!}</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.text.buttons.save')</button>
                    <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.text.buttons.cancel')</a>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.name')</label>
                        <input type="text" id="name" name="name" class="form-control" value="{!! old('name',$role->name) !!}">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.level')</label>
                        <input type="number" id="level" name="level" class="form-control" value="{!! old('level',$role->level) !!}">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.description')</label>
                        <textarea name="description" id="description" class="form-control" rows="4">{!! old('description',$role->description) !!}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
</div>
@stop

resources/views/role/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Roles Management</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <a href="{!! route('roles.create') !!}" class="btn btn-primary btn-flat"><i class="fa fa-plus"></i> @lang('task.text.buttons.add_role')</a>
                </div>
            </div>
            <div class="box-body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@lang('task.text.labels.name')</th>
                            <th>@lang('task.text.labels.description')</th>
                            <th>@lang('task.text.labels.level')</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($roles as $role)
                    <tr>
                        <td>{{ $role->name }}</td>
                        <td>{{ $role->description }}</td>
                        <td>{{ $role->level }}</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a href="{!! route('roles.edit',$role->id) !!}" class="btn btn-default btn-flat">
                                    <i class="fa fa-edit"></i> @lang('task.text.buttons.edit')
                                </a>
                                <button class="btn btn-danger btn-flat" data-btn-type="delete" data-url="{!! route('roles.destroy',$role->id) !!}" data-toggle="confirmation"><i class="fa fa-trash"></i> @lang('task.text.buttons.delete')</button>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4"><p class="text-center">@lang('task.no.record')</p></td>
                    </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            @if($paginate = $roles->render())
            <div class="box-footer">
                {!! $paginate !!}
            </div>
            @endif
        </div>
    </div>
</div>
@stop