app/Http/routes.php
<?php


Route::get('login', 'Auth\AuthController@login');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

Route::group(['middleware' => 'auth'], function () {

    Route::get('not-found', 'HomeController@notFound');

    Route::get('/', [
        'as'   => 'home',
        'uses' => 'HomeController@index'
    ]);
    Route::get('my-tasks', [
        'as'   => 'tasks',
        'uses' => 'HomeController@tasks'
    ]);
    Route::get('my-tasks/{id}', [
        'as'   => 'task',
        'uses' => 'HomeController@task'
    ]);
    Route::post('my-tasks/{id}', [
        'as'   => 'task.update',
        'uses' => 'HomeController@taskSave'
    ]);
    Route::get('calendar-tasks', [
        'as'   => 'home.calendar.tasks',
        'uses' => 'HomeController@calendarTasks'
    ]);

    Route::resource('clients', 'ClientController',
        ['only' => ['index', 'show']]);

    Route::get('clients/login/{id}', [
        'as'   => 'clients.login',
        'uses' => 'ClientController@login'
    ]);
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/search/client', [
        'as'   => 'tasks.find.client',
        'uses' => 'TaskController@findClient'
    ]);

    Route::resource('configuration', 'ConfigurationController');

    Route::get('tasks/note/{id}', [
        'as'   => 'tasks.note',
        'uses' => 'TaskController@note'
    ]);
    Route::post('tasks/note/{id}', [
        'as'   => 'tasks.note.save',
        'uses' => 'TaskController@noteSave'
    ]);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');

});

app/Http/Controllers/UserController.php
<?php

namespace SAPM\Http\Controllers;

use Prettus\Validator\Exceptions\ValidatorException;
use SAPM\Repositories\RoleRepository;
use SAPM\Repositories\UserRepository;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $user;

    /**
     * @var RoleRepository
     */
    protected $role;

    /**
     * @param UserRepository $repository
     * @param RoleRepository $roleRepository
     */
    public function __construct(UserRepository $repository, RoleRepository $roleRepository)
    {
        $this->user = $repository;
        $this->role = $roleRepository;
        $this->middleware('role:administrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = $this->user->paginate();

        $this->setTitleOrDescription('Users');
        return $this->view('index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $roles = $this->role->lists('name', 'id')->all();

        $this->setTitleOrDescription('Users');
        return $this->view('create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $this->user->addUser($request->all());
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('users.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $user  = $this->user->find($id);
        $roles = $this->role->lists('name', 'id')->all();

        $this->setTitleOrDescription('Users');
        return $this->view('edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->user->editUser($request->all(), $id);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag());
        }

        return $this->redirectRoute('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->user->delete($id);
    }
}

resources/views/user/create.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        {!! Form::open(['route' => 'users.store','method' => 'POST']) !!}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Creación de Usuarios</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.texto.botones.guardar')</button>
                    <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.texto.botones.cancelar')</a>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        <label for="name">@lang('task.texto.labels.nombre')</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="email">@lang('task.texto.labels.email')</label>
                        <input type="email" name="email" class="form-control" value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label for="password">@lang('task.texto.labels.password')</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">@lang('task.texto.labels.password_confirmar')</label>
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="role">@lang('task.texto.labels.rol')</label>
                        {!! Form::select('role',$roles + ["" => trans('task.texto.selecciona_rol')],old('role'),['class' => 'form-control','id' => 'form-control']) !!}
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@stop

resources/views/user/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        {!! Form::open(['route' => ['users.update',$user->id],'method' => 'PUT']) !!}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">User Edit - {{ $user->name }}</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <button class="btn btn-primary btn-flat" type="submit"><i class="fa fa-save"></i> @lang('task.text.buttons.save')</button>
                    <a class="btn btn-danger btn-flat" href="{!! URL::previous() !!}"><i class="fa fa-remove"></i> @lang('task.text.buttons.cancel')</a>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        <label for="name">@lang('task.text.labels.name')</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ old('name',$user->name) }}">
                    </div>
                    <div class="form-group">
                        <label for="email">@lang('task.text.labels.email')</label>
                        <input type="email" name="email" class="form-control" value="{{ old('email',$user->email) }}">
                    </div>
                    <div class="form-group">
                        <label for="password">@lang('task.text.labels.password')</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">@lang('task.text.labels.password_confirmation')</label>
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="role">@lang('task.text.labels.role')</label>
                        {!! Form::select('role',$roles + ["" => trans('task.text.select_role')],old('role',$user->roles->first()->id),['class' => 'form-control','id' => 'form-control']) !!}
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@stop

resources/views/user/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Control de Usuarios</h3>
                <div class="btn-group btn-group-xs pull-right">
                    <a href="{!! route('users.create') !!}" class="btn btn-primary btn-flat"><i class="fa fa-user-plus"></i> @lang('task.texto.botones.agregar_usuario')</a>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>@lang('task.texto.labels.nombre')</th>
                            <th>@lang('task.texto.labels.rol')</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->roles->first()->name }}</td>
                        <td>
                        <div class="btn-group btn-group-xs">
                            <a href="{!! route('users.edit',$user->id) !!}" class="btn btn-default btn-flat">
                                <i class="fa fa-edit"></i> @lang('task.texto.botones.editar')
                            </a>
                            <button class="btn btn-danger btn-flat" data-btn-type="delete" data-url="{!! route('users.destroy',$user->id) !!}" data-toggle="confirmation"><i class="fa fa-trash"></i> @lang('task.texto.botones.borrar')</button>
                        </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="3">@lang('task.no.guardar')</td>
                    </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            @if( $paginate = $users->render() )
            <div class="box-footer">
                {!! $paginate !!}
            </div>
            @endif
        </div>
    </div>
</div>
@stop