app/Http/routes.php
<?php


Route::get('login', 'Auth\AuthController@login');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

Route::group(['middleware' => 'auth'], function () {

    Route::get('not-found', 'HomeController@notFound');

    Route::get('/', [
        'as'   => 'home',
        'uses' => 'HomeController@index'
    ]);
    Route::get('my-tasks', [
        'as'   => 'tasks',
        'uses' => 'HomeController@tasks'
    ]);
    Route::get('my-tasks/{id}', [
        'as'   => 'task',
        'uses' => 'HomeController@task'
    ]);
    Route::post('my-tasks/{id}', [
        'as'   => 'task.update',
        'uses' => 'HomeController@taskSave'
    ]);
    Route::get('calendar-tasks', [
        'as'   => 'home.calendar.tasks',
        'uses' => 'HomeController@calendarTasks'
    ]);

    Route::resource('clients', 'ClientController',
        ['only' => ['index', 'show']]);

    Route::get('clients/login/{id}', [
        'as'   => 'clients.login',
        'uses' => 'ClientController@login'
    ]);
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/search/client', [
        'as'   => 'tasks.find.client',
        'uses' => 'TaskController@findClient'
    ]);

    Route::resource('configuration', 'ConfigurationController');

    Route::get('tasks/note/{id}', [
        'as'   => 'tasks.note',
        'uses' => 'TaskController@note'
    ]);
    Route::post('tasks/note/{id}', [
        'as'   => 'tasks.note.save',
        'uses' => 'TaskController@noteSave'
    ]);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');

});

resources/views/layouts/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{!! url('/') !!}" class="logo">
        <span class="logo-mini">{!! config('task.title.short') !!}</span>
        <span class="logo-lg">{!! config('task.title.long') !!}</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">@lang('task.text.toggle_navigation')</span>
        </a>

        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Tasks: style can be found in dropdown.less -->
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-info">{!! $userTasks->openTasks()->count() !!}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">@lang('task.texto.tienes_tareas',['task' => $userTasks->openTasks()->count()])</li>
                        <li>
                            <ul class="menu">
                                @forelse($userTasks->openTasks()->take(4)->get() as $task)
                                <li><!-- Task item -->
                                    <a href="#"><h3>{{ $task->name }}</h3></a>
                                    <div class="progress xs">
                                        <div class="progress-bar" style="width: 100%;background-color: {!! config('task.prioridad.' . $task->priority) !!}" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">100% Completado</span>
                                        </div>
                                    </div>
                                </li><!-- end task item -->
                                @empty
                                <li>
                                    <a href="#"><h3 class="text-center">@lang('task.no.guardar')</h3></a>
                                </li>
                                @endforelse
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="{!! route('tasks') !!}">@lang('task.texto.mirar_todas_las_tareas')</a>
                        </li>
                    </ul>
                </li>

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset("/img/default.png") }}" class="user-image" alt="User Image"/>
                        <span class="hidden-xs">{!! auth()->user()->name !!}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset("/img/default.png") }}" class="img-circle" alt="User Image" />
                            <p>
                                {!! auth()->user()->name !!}
                                <small>@lang('task.texto.miembro_desde',['date' => auth()->user()->created_at->format('M.Y')])</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{!! route('tasks') !!}" class="btn btn-default btn-xs btn-flat">@lang('task.texto.mis_tareas')</a>
                            </div>
                            <div class="pull-right">
                                <a href="/logout" class="btn btn-default btn-xs btn-flat">@lang('task.texto.salir')</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title or config('task.title.long') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{{ asset("/assets/admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="{!! asset('assets/admin-lte/plugins/fullcalendar/fullcalendar.min.css') !!}" rel="stylesheet" type="text/css" />
    <link href="{!! asset('assets/admin-lte/plugins/fullcalendar/fullcalendar.print.css') !!}" rel="stylesheet" type="text/css" media="print" />
    <link href="{{ asset("/assets/admin-lte/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/assets/admin-lte/dist/css/skins/skin-black-light.min.css")}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/assets/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css")}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{!! asset('css/style.css') !!}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-black-light sidebar-mini">
<div class="wrapper">
    @include('layouts.header')
    @include('layouts.sidebar')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ $title or config('task.title.long') }}
                <small>{{ $description or null }}</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            @include('errors.validator')
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
</div><!-- ./wrapper -->

<script src="{{ asset("/assets/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js") }}" type="text/javascript"></script>
<script src="{{ asset("/assets/admin-lte/bootstrap/js/bootstrap.min.js") }}" type="text/javascript"></script>
<script src="{{ asset("/assets/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js") }}" type="text/javascript"></script>
<script src="{{ asset('/assets/admin-lte/plugins/slimScroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset("/assets/typeahead.js/dist/typeahead.bundle.min.js") }}" type="text/javascript"></script>
<script src="{{ asset("/js/bootstrap-confirmation.min.js") }}" type="text/javascript"></script>
<script src="{{ asset("/js/moment-with-locales.min.js") }}" type="text/javascript"></script>
<script src="{!! asset('assets/admin-lte/plugins/fullcalendar/fullcalendar.min.js') !!}" type="text/javascript"></script>
<script src="{!! asset('assets/admin-lte/plugins/fullcalendar/lang-all.js') !!}" type="text/javascript"></script>
<script src="{{ asset("/js/script.js") }}" type="text/javascript"></script>
<script src="{{ asset("/assets/admin-lte/dist/js/app.min.js") }}" type="text/javascript"></script>
@yield('js')
</body>
</html>

resources/views/layouts/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset("/img/default.png") }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{!! auth()->user()->name !!}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> @lang('task.texto.online')</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">@lang('task.text.navigation')</li>
            <li><a href="{!! url('/') !!}"><i class="fa fa-dashboard"></i><span>@lang('task.titulo.administrador')</span></a></li>
            @if( auth()->user()->level() == 10 )
            <li><a href="{!! route('tasks.index') !!}"><i class="fa fa-tasks"></i><span>@lang('task.titulo.tareas')</span></a></li>
            <li><a href="{!! route('clients.index') !!}"><i class="fa fa-user"></i><span>@lang('task.titulo.maestrantes')</span></a></li>
            <li><a href="{!! route('clients.index') !!}"><i class="fa fa-user"></i><span>@lang('task.titulo.diplomados')</span></a></li>
            <li><a href="{!! route('categories.index') !!}"><i class="fa fa-th-list"></i><span>@lang('task.titulo.categorias')</span></a></li>
            <li class="treeview">
                <a href="#"><i class="fa fa-users"></i><span>@lang('task.titulo.control_usuarios')</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{!! route('users.index') !!}"><i class="fa fa-circle-o"></i> @lang('task.titulo.usuarios')</a></li>
                    <li><a href="{!! route('roles.index') !!}"><i class="fa fa-circle-o"></i> @lang('task.titulo.roles')</a></li>
                </ul>
            </li>
            {{--@else--}}
            {{--<li><a href="{!! route('tasks') !!}"><i class="fa fa-tasks"></i><span>@lang('task.text.my_tasks')</span></a></li>--}}
            @endif
            @if( auth()->user()->level() == 1)
                <li><a href="{!! route('tasks.index') !!}"><i class="fa fa-tasks"></i><span>@lang('task.titulo.tareas')</span></a></li>
                <li><a href="{!! route('configuration.index') !!}"><i class="fa fa-tasks"></i><span>@lang('task.titulo.configuraciones')</span></a></li>
            @endif
            <li class="header">@lang('task.texto.prioridad')</li>
            @foreach(config('task.priority') as $key => $color)
            <li>
                <a href="javascript:void(0)">
                    <i class="fa fa-circle" style="color: {!! $color !!}"></i> <span>{!! $key !!}</span>
                </a>
            </li>
            @endforeach
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>